import { useState, useEffect } from "react";
import type { ReactElement } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

import { LayoutOpenAR } from "~/components/app";
import { Box, Text, Button } from "@chakra-ui/react";
import { useAuthentication, useTypedSelector, useWalletLogin } from "~/hooks";
import { WalletControl } from "~/components/app/shared";

const OpenARLogin = () => {
  const {
    account,
    walletLoginRequestSignature,
    walletLoginError,
    walletDisconnect,
    library,
  } = useWalletLogin();
  const [appUser] = useAuthentication();
  const stateUser = useTypedSelector(({ user }) => user);
  const stateCrypto = useTypedSelector(({ crypto }) => crypto);
  const router = useRouter();
  const [isLoggingIn, setIsLoggingIn] = useState(false);

  let navigating = false;

  if (appUser && stateUser.authenticated) {
    router.push("/openar/");
    navigating = true;
  }

  useEffect(() => {
    if (!library || !library?.provider) {
      if (stateCrypto.signatureRequired) {
        walletDisconnect();
      }
    }
  }, [
    library,
    walletDisconnect,
    stateUser.justConnected,
    stateCrypto.signatureRequired,
  ]);

  useEffect(() => {
    if (library || library?.provider) {
      if (stateUser.justConnected && stateCrypto.signatureRequired) {
        router.push("/openar/login");
      }
    }
  }, [
    library,
    walletDisconnect,
    stateUser.justConnected,
    router,
    stateCrypto.signatureRequired,
  ]);

  return (
    <Box p="6">
      <Head>
        <title>OpenAR </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text mb="4">Hello, please click login to connect to your platform.</Text>

      {!stateUser.justConnected &&
        (!appUser || !stateUser.authenticated) &&
        !navigating && (
          <Box>
            <WalletControl />
          </Box>
        )}
    </Box>
  );
};

OpenARLogin.getLayout = function getLayout(page: ReactElement) {
  return <LayoutOpenAR>{page}</LayoutOpenAR>;
};

export default OpenARLogin;
