import type { ReactElement } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { LayoutOpenAR } from "~/components/app";
import { Box } from "@chakra-ui/layout";
import { useConfigContext } from "~/providers";

// import { useEthers, useEtherBalance } from "@usedapp/core";
// import { formatUnits } from "@ethersproject/units";

const OpenARDashboard = () => {
  // const { activateBrowserWallet, deactivate, account } = useEthers();
  // const userBalance = useEtherBalance(account);
  // const stakingBalance = useEtherBalance(STAKING_CONTRACT);
  const appConfig = useConfigContext();
  
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          Please connect to your wallet to access this page. 
{`${process.env.NEXT_PUBLIC_INFURA_URL}`}

          {}
        </div>
      </main>

      <footer>
        FOOOTERE 
      </footer>
    </Box>
  );
};

OpenARDashboard.getLayout = function getLayout(page: ReactElement) {
  return <LayoutOpenAR>{page}</LayoutOpenAR>;
};

export default OpenARDashboard;
