import type { ReactElement } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { LayoutOpenAR } from "~/components/app";
import { Box } from "@chakra-ui/layout";
import { useConfigContext } from "~/providers";

// import { useEthers, useEtherBalance } from "@usedapp/core";
// import { formatUnits } from "@ethersproject/units";

const OpenARDashboard = () => {
  // const { activateBrowserWallet, deactivate, account } = useEthers();
  // const userBalance = useEtherBalance(account);
  // const stakingBalance = useEtherBalance(STAKING_CONTRACT);
  const appConfig = useConfigContext();
  
  return (
    <Box>
      <Head>
        <title>TODO: OpenAR Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {!account && (
        <button onClick={() => activateBrowserWallet()}> Connect </button>
      )}
      {account && <button onClick={deactivate}> Disconnect </button>}

      {stakingBalance && (
        <p>ETH2 staking balance: {formatUnits(stakingBalance, 18)} ETH </p>
      )}
      {account && <p>Account: {account}</p>}
      {userBalance && (
        <p>Ether balance: {formatUnits(userBalance, 18)} ETH </p>
      )} */}

      {`${process.env.NEXT_PUBLIC_INFURA_ID}`}
  safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>safkakfdssadjfhjkds<br/>
         
      {}
    </Box>
  );
};

OpenARDashboard.getLayout = function getLayout(page: ReactElement) {
  return <LayoutOpenAR>{page}</LayoutOpenAR>;
};

export default OpenARDashboard;
