import type { ReactElement } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { LayoutOpenAR } from "~/components/app";
import { Box } from "@chakra-ui/layout";
import { useConfigContext } from "~/providers";

// import { useEthers, useEtherBalance } from "@usedapp/core";
// import { formatUnits } from "@ethersproject/units";

const OpenARWelcome = () => {
  // const { activateBrowserWallet, deactivate, account } = useEthers();
  // const userBalance = useEtherBalance(account);
  // const stakingBalance = useEtherBalance(STAKING_CONTRACT);
  const appConfig = useConfigContext();
  
  return (
    <Box>
      <Head>
        <title>TODO: OpenAR Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Show onboarding form. Ask for email and pseudonym promise token ... 
      {}
    </Box>
  );
};

OpenARWelcome.getLayout = function getLayout(page: ReactElement) {
  return <LayoutOpenAR>{page}</LayoutOpenAR>;
};

export default OpenARWelcome;
