import type { ReactElement } from "react";
import Head from "next/head";

import { LayoutSite } from "~/components/app";
import { Box } from "@chakra-ui/react";
import Link from "next/link";
import { WalletControl } from "~/components/app/shared"

export const Home = () => {
  return (
    <Box>
      <Head>
        <title>TODO: OpenAR Title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/openar/">
        <a>OpenAR</a>
      </Link>
      Some great homepage content ...
      <WalletControl />
    </Box>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <LayoutSite>{page}</LayoutSite>;
};

export default Home;
