import type { ReactElement } from 'react'
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { LayoutSite } from "~/components/app";
import { Box } from '@chakra-ui/react';


// import { useEthers, useEtherBalance } from "@usedapp/core";
// import { formatUnits } from "@ethersproject/units";

const STAKING_CONTRACT = "0x00000000219ab540356cBB839Cbe05303d7705Fa";

export const Home = () => {
  // const { activateBrowserWallet, deactivate, account } = useEthers();
  // const userBalance = useEtherBalance(account);
  // const stakingBalance = useEtherBalance(STAKING_CONTRACT);

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     Some great homepage content ... 
    </Box>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <LayoutSite>
      {page}
    </LayoutSite>
  )
}

export default Home;
